---
title: "Nonparametric Goodness-of-Fit Tests for ISV cell numbers"
author: "Wolfgang Giese"
date: "February 25, 2021"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
knitr::opts_chunk$set(warning = FALSE, message = FALSE) 
library(dgof)
library(ggplot2)
library(rjson)
library(plotrix)
library(plyr)

show_ks_details=TRUE
```

```{r read_cell_number_distributions, echo=FALSE}
path = getwd()
filename <- paste(path,"../../02_derived_data/mitosis_and_cell_number_data/mitosis_cell_number_distributions.json", sep = "/")
#print(paste("Filename: ",filename))
cell_number_json <- fromJSON(file = filename)
#print(cell_number_json)
subfolder <- "statistics_plots/"
color_aISV <- "#FFDACC"
color_vISV <- "#CCF2F2"
color_control_background <- "#E2E2E2"

```

## Comparison of cell numbers aISV vs vISV for all conditions

```{r plot_cell_number_distributions_control, echo=FALSE}

res <- dgof::ks.test(cell_number_json$cell_number$control$aISV, cell_number_json$cell_number$control$vISV)


text <- sprintf("p-value : %s", res$p.value)

vessel_type <- c()
vessel_type[1:length(cell_number_json$cell_number$control$aISV)] <- "aISV"
vessel_type[length(cell_number_json$cell_number$control$aISV)+1:length(cell_number_json$cell_number$control$vISV)] <- "vISV"

df <- data.frame(vessel_type, c(cell_number_json$cell_number$control$aISV,cell_number_json$cell_number$control$vISV))

colnames(df) <- c("vessel_type","counts")
mu <- ddply(df, "vessel_type", summarise, grp.mean=mean(counts))
sigma <- ddply(df, "vessel_type", summarise, grp.std=sd(counts))
mu_sigma_aISV <- paste(mu$vessel_type[1],"mean :" ,mu$grp.mean[1], "sd :", sigma$grp.std[1], sep =" ")
mu_sigma_vISV <- paste(mu$vessel_type[2],"mean :" ,mu$grp.mean[2], "sd :", sigma$grp.std[2], sep =" ")

pdf(paste0(subfolder, 'cell_number_control_GOF.pdf'))

p <-  ggplot(df, aes(x=counts, fill=vessel_type, color=vessel_type) ) + 
      geom_histogram(position="dodge", binwidth=1.0) +
      geom_vline(data=mu, aes(xintercept=grp.mean, color=vessel_type),
      linetype="dashed") #+
      #theme(axis.line = element_line(),
      #      panel.background = element_blank())

p <- p + labs(title = "Comparison control aISV vs. vISV",
              subtitle = "Cell number count per ISV",
              caption =  sprintf("p-value : %s \n %s \n %s", res$p.value, mu_sigma_aISV, mu_sigma_vISV) )  + 
    ylab("ISV count") + 
    xlim(0,max(df$counts))+
    scale_x_discrete(name ="Cell number per ISV", 
    limits=0:max(df$counts) )+
    scale_color_manual(values=c("red","blue","#999999")) +
    scale_fill_manual(values=c(color_aISV, color_vISV, "#999999"))

p

dev.off()

p

if (show_ks_details){
  print("results of discrete KS-test:")
  print(res)
}

#print(paste("vessel type", mu$vessel_type[1],"mean :" ,mu$grp.mean[1], "sd :", sigma$grp.std[1], sep =" "))
#print(paste("vessel type", mu$vessel_type[2],"mean :" ,mu$grp.mean[2], "sd :", sigma$grp.std[2], sep =" "))
#print(paste("Standard deviation for ", sigma$vessel_type[1],":" , sigma$grp.std[1],sep =" "))
#print(paste("Mean for ", mu$vessel_type[2],":" ,mu$grp.mean[2],sep =" "))
#print(paste("Standard deviation for ", sigma$vessel_type[2],":" , sigma$grp.std[2],sep =" "))
```

```{r plot_cell_number_distributions_Wasp, echo=FALSE}

res <- dgof::ks.test(cell_number_json$cell_number$`WaspI [100uM]`$aISV, cell_number_json$cell_number$`WaspI [100uM]`$vISV)


text <- sprintf("p-value : %s", res$p.value)

vessel_type <- c()
vessel_type[1:length(cell_number_json$cell_number$`WaspI [100uM]`$aISV)] <- "aISV"
vessel_type[length(cell_number_json$cell_number$`WaspI [100uM]`$aISV)+1:length(cell_number_json$cell_number$`WaspI [100uM]`$vISV)] <- "vISV"

df <- data.frame(vessel_type, c(cell_number_json$cell_number$`WaspI [100uM]`$aISV,cell_number_json$cell_number$`WaspI [100uM]`$vISV))

colnames(df) <- c("vessel_type","counts")
mu <- ddply(df, "vessel_type", summarise, grp.mean=mean(counts))
sigma <- ddply(df, "vessel_type", summarise, grp.std=sd(counts))
mu_sigma_aISV <- paste(mu$vessel_type[1],"mean :" ,mu$grp.mean[1], "sd :", sigma$grp.std[1], sep =" ")
mu_sigma_vISV <- paste(mu$vessel_type[2],"mean :" ,mu$grp.mean[2], "sd :", sigma$grp.std[2], sep =" ")

pdf(paste0(subfolder, 'cell_number_Wasp1_GOF.pdf'))

p <-  ggplot(df, aes(x=counts, fill=vessel_type, color=vessel_type) ) + 
      geom_histogram(position="dodge", binwidth=1.0) +
      geom_vline(data=mu, aes(xintercept=grp.mean, color=vessel_type),
      linetype="dashed")

p <- p + labs(title = "Comparison aISV vs. vISV for WaspI [100uM]",
              subtitle = "Cell number count per ISV",
              caption =  sprintf("p-value : %s \n %s \n %s", res$p.value, mu_sigma_aISV, mu_sigma_vISV) )  + 
    ylab("ISV count") + 
    xlim(0,max(df$counts))+
    scale_x_discrete(name ="Cell number count per ISV", 
    limits=0:max(df$counts) )+
    scale_color_manual(values=c("red","blue","#999999")) +
    scale_fill_manual(values=c(color_aISV, color_vISV, "#999999"))

p

dev.off()

p

if (show_ks_details){
  print("results of discrete KS-test:")
  print(res)
}
```

```{r plot_cell_number_distributions_Gata1, echo=FALSE}

res <- dgof::ks.test(cell_number_json$cell_number$Gata1$aISV, cell_number_json$cell_number$Gata1$vISV)


text <- sprintf("p-value : %s", res$p.value)

vessel_type <- c()
vessel_type[1:length(cell_number_json$cell_number$Gata1$aISV)] <- "aISV"
vessel_type[length(cell_number_json$cell_number$Gata1$aISV)+1:length(cell_number_json$cell_number$Gata1$vISV)] <- "vISV"

df <- data.frame(vessel_type, c(cell_number_json$cell_number$Gata1$aISV,cell_number_json$cell_number$Gata1$vISV))

colnames(df) <- c("vessel_type","counts")
mu <- ddply(df, "vessel_type", summarise, grp.mean=mean(counts))
sigma <- ddply(df, "vessel_type", summarise, grp.std=sd(counts))
mu_sigma_aISV <- paste(mu$vessel_type[1],"mean :" ,mu$grp.mean[1], "sd :", sigma$grp.std[1], sep =" ")
mu_sigma_vISV <- paste(mu$vessel_type[2],"mean :" ,mu$grp.mean[2], "sd :", sigma$grp.std[2], sep =" ")

pdf(paste0(subfolder, 'cell_number_Gata1_GOF.pdf'))

p <-  ggplot(df, aes(x=counts, fill=vessel_type, color=vessel_type) ) + 
      geom_histogram(position="dodge", binwidth=1.0) +
      geom_vline(data=mu, aes(xintercept=grp.mean, color=vessel_type),
      linetype="dashed")

p <- p + labs(title = "Comparison aISV vs. vISV for Gata1",
              subtitle = "Cell number count per ISV",
              caption =  sprintf("p-value : %s \n %s \n %s", res$p.value, mu_sigma_aISV, mu_sigma_vISV) )  + 
    ylab("ISV count") + 
    xlim(0,max(df$counts))+
    scale_x_discrete(name ="Cell number count per ISV", 
    limits=0:max(df$counts) )+
    scale_color_manual(values=c("red","blue","#999999")) +
    scale_fill_manual(values=c(color_aISV, color_vISV, "#999999"))

p

dev.off()

p

if (show_ks_details){
  print("results of discrete KS-test:")
  print(res)
}
```

```{r plot_cell_number_distributions_Gata1_Wasp1, echo=FALSE}

res <- dgof::ks.test(cell_number_json$cell_number$Gata1_Wasp1$aISV, cell_number_json$cell_number$Gata1_Wasp1$vISV)


text <- sprintf("p-value : %s", res$p.value)

vessel_type <- c()
vessel_type[1:length(cell_number_json$cell_number$Gata1_Wasp1$aISV)] <- "aISV"
vessel_type[length(cell_number_json$cell_number$Gata1_Wasp1$aISV)+1:length(cell_number_json$cell_number$Gata1_Wasp1$vISV)] <- "vISV"

df <- data.frame(vessel_type, c(cell_number_json$cell_number$Gata1_Wasp1$aISV,cell_number_json$cell_number$Gata1_Wasp1$vISV))

colnames(df) <- c("vessel_type","counts")
mu <- ddply(df, "vessel_type", summarise, grp.mean=mean(counts))
sigma <- ddply(df, "vessel_type", summarise, grp.std=sd(counts))
mu_sigma_aISV <- paste(mu$vessel_type[1],"mean :" ,mu$grp.mean[1], "sd :", sigma$grp.std[1], sep =" ")
mu_sigma_vISV <- paste(mu$vessel_type[2],"mean :" ,mu$grp.mean[2], "sd :", sigma$grp.std[2], sep =" ")

pdf(paste0(subfolder, 'cell_number_Gata1-Wasp1_GOF.pdf'))

p <-  ggplot(df, aes(x=counts, fill=vessel_type, color=vessel_type) ) + 
      geom_histogram(position="dodge", binwidth=1.0) +
      geom_vline(data=mu, aes(xintercept=grp.mean, color=vessel_type),
      linetype="dashed")

p <- p + labs(title = "Comparison aISV vs. vISV for Gata1-Wasp1",
              subtitle = "Cell number count per ISV",
              caption =  sprintf("p-value :  %s \n %s \n %s", res$p.value, mu_sigma_aISV, mu_sigma_vISV) )  + 
    ylab("ISV count") + 
    xlim(0,max(df$counts))+
    scale_x_discrete(name ="Cell number per ISV", 
    limits=0:max(df$counts) )+
    scale_color_manual(values=c("red","blue","#999999")) +
    scale_fill_manual(values=c(color_aISV, color_vISV, "#999999"))

p

dev.off()

p

if (show_ks_details){
  print("results of discrete KS-test:")
  print(res)
}
```

## Comparison of cell number to DLAV between conditions for aISV and vISV

```{r plot_cell_number_distributions_WASP_vs_Control_aISV, echo=FALSE}

res <- dgof::ks.test(cell_number_json$cell_number$control$aISV, cell_number_json$cell_number$`WaspI [100uM]`$aISV)


text <- sprintf("p-value : %s", res$p.value)

condition <- c()
condition[1:length(cell_number_json$cell_number$control$aISV)] <- "control"
condition[length(cell_number_json$cell_number$control$aISV)+1:length(cell_number_json$cell_number$`WaspI [100uM]`$aISV)] <- "Wasp"

df <- data.frame(condition, c(cell_number_json$cell_number$control$aISV,cell_number_json$cell_number$`WaspI [100uM]`$aISV))

colnames(df) <- c("condition","counts")
mu <- ddply(df, "condition", summarise, grp.mean=mean(counts))
sigma <- ddply(df, "condition", summarise, grp.std=sd(counts))
mu_sigma_cond1 <- paste(mu$condition[1],"mean :" ,mu$grp.mean[1], "sd :", sigma$grp.std[1], sep =" ")
mu_sigma_cond2 <- paste(mu$condition[2],"mean :" ,mu$grp.mean[2], "sd :", sigma$grp.std[2], sep =" ")

pdf(paste0(subfolder, 'cell_number_control_vs_Wasp1_aISV_GOF.pdf'))

p <-  ggplot(df, aes(x=counts, fill=condition, color=condition) ) + 
      geom_histogram(position="dodge", binwidth=1.0) +
      geom_vline(data=mu, aes(xintercept=grp.mean, color=condition),
      linetype="dashed")

p <- p + labs(title = "Comparison control vs. WaspI [100uM] for aISVs",
              subtitle = "Cell number count per ISV",
              caption =  sprintf("p-value : %s \n %s \n %s", res$p.value, mu_sigma_cond1, mu_sigma_cond2))  + 
    ylab("ISV count") + 
    xlim(0,max(df$counts))+
    scale_x_discrete(name ="Cell number count per ISV", 
    limits=0:max(df$counts) )+
    scale_color_manual(values=c("black", "red", "#999999")) +
    scale_fill_manual(values=c(color_control_background, color_aISV, "#999999"))

p

dev.off()

p


if (show_ks_details){
  print("results of discrete KS-test:")
  print(res)
}
```

```{r plot_cell_number_distributions_WASP_vs_Control_vISV, echo=FALSE}

res <- dgof::ks.test(cell_number_json$cell_number$control$vISV, cell_number_json$cell_number$`WaspI [100uM]`$vISV)


text <- sprintf("p-value : %s", res$p.value)

condition <- c()
condition[1:length(cell_number_json$cell_number$control$vISV)] <- "control"
condition[length(cell_number_json$cell_number$control$vISV)+1:length(cell_number_json$cell_number$`WaspI [100uM]`$vISV)] <- "Wasp"

df <- data.frame(condition, c(cell_number_json$cell_number$control$vISV,cell_number_json$cell_number$`WaspI [100uM]`$vISV))

colnames(df) <- c("condition","counts")
mu <- ddply(df, "condition", summarise, grp.mean=mean(counts))
sigma <- ddply(df, "condition", summarise, grp.std=sd(counts))
mu_sigma_cond1 <- paste(mu$condition[1],"mean :" ,mu$grp.mean[1], "sd :", sigma$grp.std[1], sep =" ")
mu_sigma_cond2 <- paste(mu$condition[2],"mean :" ,mu$grp.mean[2], "sd :", sigma$grp.std[2], sep =" ")


pdf(paste0(subfolder, 'cell_number_control_vs_Wasp1_vISV_GOF.pdf'))

p <-  ggplot(df, aes(x=counts, fill=condition, color=condition) ) + 
      geom_histogram(position="dodge", binwidth=1.0) +
      geom_vline(data=mu, aes(xintercept=grp.mean, color=condition),
      linetype="dashed")

p <- p + labs(title = "Comparison control vs. WaspI [100uM] for vISVs",
              subtitle = "Cell number count per ISV",
              caption =  sprintf("p-value : %s \n %s \n %s", res$p.value, mu_sigma_cond1, mu_sigma_cond2))  + 
    ylab("ISV count") + 
    xlim(0,max(df$counts))+
    scale_x_discrete(name ="Cell number count per ISV", 
    limits=0:max(df$counts) )+
    scale_color_manual(values=c("black", "blue", "#999999")) +
    scale_fill_manual(values=c(color_control_background, color_vISV, "#999999"))

p

dev.off()

p

if (show_ks_details){
  print("results of discrete KS-test:")
  print(res)
}
```


```{r plot_cell_number_distributions_Control_vs_Gata1_aISV, echo=FALSE}

res <- dgof::ks.test(cell_number_json$cell_number$control$aISV, cell_number_json$cell_number$Gata1$aISV)


text <- sprintf("p-value : %s", res$p.value)

condition <- c()
condition[1:length(cell_number_json$cell_number$control$aISV)] <- "control"
condition[length(cell_number_json$cell_number$control$aISV)+1:length(cell_number_json$cell_number$Gata1$aISV)] <- "Gata1"

df <- data.frame(condition, c(cell_number_json$cell_number$control$aISV,cell_number_json$cell_number$Gata1$aISV))

colnames(df) <- c("condition","counts")
mu <- ddply(df, "condition", summarise, grp.mean=mean(counts))
sigma <- ddply(df, "condition", summarise, grp.std=sd(counts))
mu_sigma_cond1 <- paste(mu$condition[1],"mean :" ,mu$grp.mean[1], "sd :", sigma$grp.std[1], sep =" ")
mu_sigma_cond2 <- paste(mu$condition[2],"mean :" ,mu$grp.mean[2], "sd :", sigma$grp.std[2], sep =" ")

pdf(paste0(subfolder, 'cell_number_control_vs_Gata1_aISV_GOF.pdf'))

p <-  ggplot(df, aes(x=counts, fill=condition, color=condition) ) + 
      geom_histogram(position="dodge", binwidth=1.0) +
      geom_vline(data=mu, aes(xintercept=grp.mean, color=condition),
      linetype="dashed")

p <- p + labs(title = "Comparison control vs. Gata1 for aISVs",
              subtitle = "Cell number count per ISV",
              caption =  sprintf("p-value : %s \n %s \n %s", res$p.value, mu_sigma_cond1, mu_sigma_cond2))  + 
    ylab("ISV count") + 
    xlim(0,max(df$counts))+
    scale_x_discrete(name ="Cell number count per ISV", 
    limits=0:max(df$counts) )+
    scale_color_manual(values=c("black", "red", "#999999")) +
    scale_fill_manual(values=c(color_control_background, color_aISV, "#999999"))
p

dev.off()

p

if (show_ks_details){
  print("results of discrete KS-test:")
  print(res)
}
```

```{r plot_cell_number_distributions_Control_vs_Gata1_vISV, echo=FALSE}

res <- dgof::ks.test(cell_number_json$cell_number$control$vISV, cell_number_json$cell_number$Gata1$vISV)


text <- sprintf("p-value : %s", res$p.value)

condition <- c()
condition[1:length(cell_number_json$cell_number$control$vISV)] <- "control"
condition[length(cell_number_json$cell_number$control$vISV)+1:length(cell_number_json$cell_number$Gata1$vISV)] <- "Gata1"

df <- data.frame(condition, c(cell_number_json$cell_number$control$vISV,cell_number_json$cell_number$Gata1$vISV))

colnames(df) <- c("condition","counts")
mu <- ddply(df, "condition", summarise, grp.mean=mean(counts))
sigma <- ddply(df, "condition", summarise, grp.std=sd(counts))
mu_sigma_cond1 <- paste(mu$condition[1],"mean :" ,mu$grp.mean[1], "sd :", sigma$grp.std[1], sep =" ")
mu_sigma_cond2 <- paste(mu$condition[2],"mean :" ,mu$grp.mean[2], "sd :", sigma$grp.std[2], sep =" ")

pdf(paste0(subfolder, 'cell_number_control_vs_Gata1_vISV_GOF.pdf'))

p <-  ggplot(df, aes(x=counts, fill=condition, color=condition) ) + 
      geom_histogram(position="dodge", binwidth=1.0) +
      geom_vline(data=mu, aes(xintercept=grp.mean, color=condition),
      linetype="dashed")

p <- p + labs(title = "Comparison control vs. Gata1 for vISVs",
              subtitle = "Cell number count per ISV",
              caption =  sprintf("p-value : %s \n %s \n %s", res$p.value, mu_sigma_cond1, mu_sigma_cond2))  + 
    ylab("ISV count") + 
    xlim(0,max(df$counts))+
    scale_x_discrete(name ="Cell number count per ISV", 
    limits=0:max(df$counts) )+
    scale_color_manual(values=c("black", "blue", "#999999")) +
    scale_fill_manual(values=c(color_control_background, color_vISV, "#999999"))

p

dev.off()

p

if (show_ks_details){
  print("results of discrete KS-test:")
  print(res)
}
```

```{r plot_cell_number_distributions_Control_vs_Gata1_Wasp1_aISV, echo=FALSE}

res <- dgof::ks.test(cell_number_json$cell_number$control$aISV, cell_number_json$cell_number$Gata1_Wasp1$aISV)


text <- sprintf("p-value : %s", res$p.value)

condition <- c()
condition[1:length(cell_number_json$cell_number$control$aISV)] <- "control"
condition[length(cell_number_json$cell_number$control$aISV)+1:length(cell_number_json$cell_number$Gata1_Wasp1$aISV)] <- "Gata1-Wasp1"

df <- data.frame(condition, c(cell_number_json$cell_number$control$aISV,cell_number_json$cell_number$Gata1_Wasp1$aISV))

colnames(df) <- c("condition","counts")
mu <- ddply(df, "condition", summarise, grp.mean=mean(counts))
sigma <- ddply(df, "condition", summarise, grp.std=sd(counts))
mu_sigma_cond1 <- paste(mu$condition[1],"mean :" ,mu$grp.mean[1], "sd :", sigma$grp.std[1], sep =" ")
mu_sigma_cond2 <- paste(mu$condition[2],"mean :" ,mu$grp.mean[2], "sd :", sigma$grp.std[2], sep =" ")

pdf(paste0(subfolder, 'cell_number_control_vs_Gata1_Wasp1_aISV_GOF.pdf'))

p <-  ggplot(df, aes(x=counts, fill=condition, color=condition) ) + 
      geom_histogram(position="dodge", binwidth=1.0) +
      geom_vline(data=mu, aes(xintercept=grp.mean, color=condition),
      linetype="dashed")

p <- p + labs(title = "Comparison control vs. Gata1-Wasp1 for aISVs",
              subtitle = "Cell number count per ISV",
              caption =  sprintf("p-value : %s \n %s \n %s", res$p.value, mu_sigma_cond1, mu_sigma_cond2))  + 
    ylab("ISV count") + 
    xlim(0,max(df$counts))+
    scale_x_discrete(name ="Cell number per ISV", 
    limits=0:max(df$counts) )+
    scale_color_manual(values=c("black", "red", "#999999")) +
    scale_fill_manual(values=c(color_control_background, color_aISV, "#999999"))

p

dev.off()

p


if (show_ks_details){
  print("results of discrete KS-test:")
  print(res)
}
```

```{r plot_cell_number_distributions_Control_vs_Gata1_Wasp1_vISV, echo=FALSE}

res <- dgof::ks.test(cell_number_json$cell_number$control$vISV, cell_number_json$cell_number$Gata1_Wasp1$vISV)


text <- sprintf("p-value : %s", res$p.value)

condition <- c()
condition[1:length(cell_number_json$cell_number$control$vISV)] <- "control"
condition[length(cell_number_json$cell_number$control$vISV)+1:length(cell_number_json$cell_number$Gata1_Wasp1$vISV)] <- "Gata1-Wasp1"

df <- data.frame(condition, c(cell_number_json$cell_number$control$vISV,cell_number_json$cell_number$Gata1_Wasp1$vISV))

colnames(df) <- c("condition","counts")
mu <- ddply(df, "condition", summarise, grp.mean=mean(counts))
sigma <- ddply(df, "condition", summarise, grp.std=sd(counts))
mu_sigma_cond1 <- paste(mu$condition[1],"mean :" ,mu$grp.mean[1], "sd :", sigma$grp.std[1], sep =" ")
mu_sigma_cond2 <- paste(mu$condition[2],"mean :" ,mu$grp.mean[2], "sd :", sigma$grp.std[2], sep =" ")

pdf(paste0(subfolder, 'cell_number_control_vs_Gata1_Wasp1_vISV_GOF.pdf'))

p <-  ggplot(df, aes(x=counts, fill=condition, color=condition) ) + 
      geom_histogram(position="dodge", binwidth=1.0) +
      geom_vline(data=mu, aes(xintercept=grp.mean, color=condition),
      linetype="dashed")

p <- p + labs(title = "Comparison control vs. Gata1-Wasp1 for vISVs",
              subtitle = "Cell number count per ISV",
              caption =  sprintf("p-value : %s \n %s \n %s", res$p.value, mu_sigma_cond1, mu_sigma_cond2))  + 
    ylab("ISV count") + 
    xlim(0,max(df$counts))+
    scale_x_discrete(name ="Cell number per ISV", 
    limits=0:max(df$counts) )+
    scale_color_manual(values=c("black", "blue", "#999999")) +
    scale_fill_manual(values=c(color_control_background, color_vISV, "#999999"))

p

dev.off()

p


if (show_ks_details){
  print("results of discrete KS-test:")
  print(res)
}
```


```{r plot_cell_number_distributions_Wasp1_vs_Gata1_Wasp1_aISV, echo=FALSE}

res <- dgof::ks.test(cell_number_json$cell_number$`WaspI [100uM]`$aISV, cell_number_json$cell_number$Gata1_Wasp1$aISV)


text <- sprintf("p-value : %s", res$p.value)

condition <- c()
condition[1:length(cell_number_json$cell_number$`WaspI [100uM]`$aISV)] <- "Wasp1"
condition[length(cell_number_json$cell_number$`WaspI [100uM]`$aISV)+1:length(cell_number_json$cell_number$Gata1_Wasp1$aISV)] <- "Gata1-Wasp1"

df <- data.frame(condition, c(cell_number_json$cell_number$`WaspI [100uM]`$aISV,cell_number_json$cell_number$Gata1_Wasp1$aISV))

colnames(df) <- c("condition","counts")
mu <- ddply(df, "condition", summarise, grp.mean=mean(counts))
sigma <- ddply(df, "condition", summarise, grp.std=sd(counts))
mu_sigma_cond1 <- paste(mu$condition[1],"mean :" ,mu$grp.mean[1], "sd :", sigma$grp.std[1], sep =" ")
mu_sigma_cond2 <- paste(mu$condition[2],"mean :" ,mu$grp.mean[2], "sd :", sigma$grp.std[2], sep =" ")

pdf(paste0(subfolder, 'cell_number_Wasp1_vs_Gata1_Wasp1_aISV_GOF.pdf'))

p <-  ggplot(df, aes(x=counts, fill=condition, color=condition) ) + 
      geom_histogram(position="dodge", binwidth=1.0) +
      geom_vline(data=mu, aes(xintercept=grp.mean, color=condition),
      linetype="dashed")

p <- p + labs(title = "Comparison `WaspI [100uM]` vs. Gata1-Wasp1 for aISVs",
              subtitle = "Cell number count per ISV",
              caption =  sprintf("p-value : %s \n %s \n %s", res$p.value, mu_sigma_cond1, mu_sigma_cond2))  + 
    ylab("ISV count") + 
    xlim(0,max(df$counts))+
    scale_x_discrete(name ="Cell number per ISV", 
    limits=0:max(df$counts) )+
    scale_color_manual(values=c("black", "red", "#999999")) +
    scale_fill_manual(values=c(color_control_background, color_aISV, "#999999"))

p

dev.off()

p


if (show_ks_details){
  print("results of discrete KS-test:")
  print(res)
}
```

```{r plot_cell_number_distributions_Wasp1_vs_Gata1_Wasp1_vISV, echo=FALSE}

res <- dgof::ks.test(cell_number_json$cell_number$`WaspI [100uM]`$vISV, cell_number_json$cell_number$Gata1_Wasp1$vISV)


text <- sprintf("p-value : %s", res$p.value)

condition <- c()
condition[1:length(cell_number_json$cell_number$`WaspI [100uM]`$vISV)] <- "Wasp1"
condition[length(cell_number_json$cell_number$`WaspI [100uM]`$vISV)+1:length(cell_number_json$cell_number$Gata1_Wasp1$vISV)] <- "Gata1-Wasp1"

df <- data.frame(condition, c(cell_number_json$cell_number$`WaspI [100uM]`$vISV,cell_number_json$cell_number$Gata1_Wasp1$vISV))

colnames(df) <- c("condition","counts")
mu <- ddply(df, "condition", summarise, grp.mean=mean(counts))
sigma <- ddply(df, "condition", summarise, grp.std=sd(counts))
mu_sigma_cond1 <- paste(mu$condition[1],"mean :" ,mu$grp.mean[1], "sd :", sigma$grp.std[1], sep =" ")
mu_sigma_cond2 <- paste(mu$condition[2],"mean :" ,mu$grp.mean[2], "sd :", sigma$grp.std[2], sep =" ")

pdf(paste0(subfolder, 'cell_number_Wasp1_vs_Gata1_Wasp1_vISV_GOF.pdf'))

p <-  ggplot(df, aes(x=counts, fill=condition, color=condition) ) + 
      geom_histogram(position="dodge", binwidth=1.0) +
      geom_vline(data=mu, aes(xintercept=grp.mean, color=condition),
      linetype="dashed")

p <- p + labs(title = "Comparison `WaspI [100uM]` vs. Gata1-Wasp1 for vISVs",
              subtitle = "Cell number count per ISV",
              caption =  sprintf("p-value : %s \n %s \n %s", res$p.value, mu_sigma_cond1, mu_sigma_cond2))  + 
    ylab("ISV count") + 
    xlim(0,max(df$counts))+
    scale_x_discrete(name ="Cell number per ISV", 
    limits=0:max(df$counts) )+
    scale_color_manual(values=c("black", "blue", "#999999")) +
    scale_fill_manual(values=c(color_control_background, color_vISV, "#999999"))

p

dev.off()

p

if (show_ks_details){
  print("results of discrete KS-test:")
  print(res)
}
```
