---
title: "Pyramid plots for ISV migration from pcv"
author: "Wolfgang Giese"
date: "March 17, 2021"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
library(ggplot2)
library(rjson)
library(plotrix)
library(tidyverse)
library(rlist)
```

## Pyramid plots for ISV migration from pcv

```{r read_migration_from_pcv, echo=FALSE}
path = getwd()
filename <- paste(path,"../../02_derived_data/mitosis_and_cell_number_data/mitosis_cell_number_distributions.json", sep = "/")
#print(paste("Filename: ",filename))
migration_json <- fromJSON(file = filename)
```

```{r plot_migration_from_to_pcv_control, echo=FALSE}

from_pcv_control_table <- table(migration_json$migration_from_pcv$control$vISV)
to_pcv_control_table <- table(migration_json$migration_to_pcv$control$vISV)
to_pcv_control_table <- data.frame(to_pcv_control_table)
print(data.frame(to_pcv_control_table))
colnames(to_pcv_control_table) <- c("value","counts_control_from_pcv")
#print(data.frame(to_pcv_table))
from_pcv_control_table <- data.frame(from_pcv_control_table)
colnames(from_pcv_control_table) <- c("value","counts_control_to_pcv")
#print(data.frame(from_pcv_table))

count_control_table <- merge(from_pcv_control_table, to_pcv_control_table, all=TRUE)
count_control_table[is.na(count_control_table)] <- 0

count_control_table ["frequency_control_from_pcv"] <- 100*count_control_table ["counts_control_from_pcv"]/sum(count_control_table["counts_control_from_pcv"])
count_control_table ["frequency_control_to_pcv"] <- 100*count_control_table ["counts_control_to_pcv"]/sum(count_control_table["counts_control_to_pcv"])
print(count_control_table)



pyramid.plot(count_control_table$frequency_control_from_pcv, count_control_table$frequency_control_to_pcv, 
             laxlab = c(0,20,40,60,80,100),
             raxlab = c(0,20,40,60,80,100),
             main = "control", 
             top.labels = c("from pcv", "migration", "to pcv"),  label=count_control_table$value,
             gap = 5, labelcex = 1.6, unit=text(0,-2,"normalized counts (%)",cex=1.6), lxcol="#CCF2F2", rxcol = "#CCF2F2")

```

```{r plot_migration_from_pcv_distributions_control_vs_Wasp1, echo=FALSE}

from_pcv_Wasp1_table <- table(migration_json$migration_from_pcv$`WaspI [100uM]`$vISV)
to_pcv_Wasp1_table <- table(migration_json$migration_from_pcv$`WaspI [100uM]`$vISV)


to_pcv_Wasp1_table <- data.frame(to_pcv_Wasp1_table)
colnames(to_pcv_Wasp1_table) <- c("value","counts_Wasp1_to_pcv")
from_pcv_Wasp1_table <- data.frame(from_pcv_Wasp1_table)
colnames(from_pcv_Wasp1_table) <- c("value","counts_Wasp1_from_pcv")

count_Wasp1_table <- merge(from_pcv_Wasp1_table, to_pcv_Wasp1_table, all=TRUE)
count_Wasp1_table [is.na(count_Wasp1_table )] <- 0
count_Wasp1_table ["frequency_Wasp1_from_pcv"] <- 100*count_Wasp1_table["counts_Wasp1_from_pcv"]/sum(count_Wasp1_table["counts_Wasp1_from_pcv"])
count_Wasp1_table ["frequency_Wasp1_to_pcv"] <- 100*count_Wasp1_table["counts_Wasp1_to_pcv"]/sum(count_Wasp1_table["counts_Wasp1_to_pcv"])

count_table <- merge(count_control_table, count_Wasp1_table, all=TRUE)
count_table[is.na(count_table)] <- 0


print(count_table)

pyramid.plot(count_table$frequency_control_from_pcv,count_table$frequency_control_to_pcv, 
             laxlab = c(0,20,40,60,80,100),
             raxlab = c(0,20,40,60,80,100),
             main = "control vs. Wasp1", 
             top.labels = c("from pcv", "migration", "  to pcv "), label=count_table$value, 
             gap = 5, labelcex = 1.6, unit=text(0,-2,"normalized counts (%)",cex=1.6), lxcol="#E2E2E2", rxcol = "#E2E2E2")

pyramid.plot(count_table$frequency_Wasp1_from_pcv,count_table$frequency_Wasp1_to_pcv,
             laxlab = c(0,20,40,60,80,100),
             raxlab = c(0,20,40,60,80,100),
             main = "control vs. Wasp1", 
             #top.labels =  c("from_pcv", "migration from pcv", "  to_pcv "), 
             label=count_table$value, space = 0.4,
             gap = 5, labelcex = 1.6, unit=text(0,-2,"Normalized counts (%)",cex=1.6), lxcol="#FFDACC", rxcol = "#CCF2F2",
             add = TRUE)

```

