---
title: "Pyramid plots for ISV migration exchange with aorta"
author: "Wolfgang Giese"
date: "March 17, 2021"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
library(ggplot2)
library(rjson)
library(plotrix)
library(tidyverse)


```

## Pyramid plots for ISV migration from aorta

```{r read_migration_from_aorta, echo=FALSE}
path = getwd()
filename <- paste(path,"../../02_derived_data/mitosis_and_cell_number_data/mitosis_cell_number_distributions.json", sep = "/")
#print(paste("Filename: ",filename))
migration_json <- fromJSON(file = filename)
subfolder <- "pyramid_plots/"
color_aISV <- "#FFDACC"
color_vISV <- "#CCF2F2"
color_control_background <- "#E2E2E2"
```

```{r plot_migration_from_to_aorta_control, echo=FALSE}

from_aorta_control_table <- table(migration_json$migration_from_aorta$control$aISV)
from_aorta_control_table <- data.frame(from_aorta_control_table)
colnames(from_aorta_control_table) <- c("value","counts_control_from_aorta")

to_aorta_control_table <- table(migration_json$migration_to_aorta$control$aISV)
to_aorta_control_table <- data.frame(to_aorta_control_table)
colnames(to_aorta_control_table) <- c("value","counts_control_to_aorta")

count_control_table <- merge(from_aorta_control_table, to_aorta_control_table, all=TRUE)
count_control_table[is.na(count_control_table)] <- 0

count_control_table ["frequency_control_from_aorta"] <- 100*count_control_table ["counts_control_from_aorta"]/sum(count_control_table["counts_control_from_aorta"])
count_control_table ["frequency_control_to_aorta"] <- 100*count_control_table ["counts_control_to_aorta"]/sum(count_control_table["counts_control_to_aorta"])

pdf(paste0(subfolder, 'migration_exchange_aorta_control.pdf'))

pyramid.plot(count_control_table$frequency_control_from_aorta, count_control_table$frequency_control_to_aorta, 
             laxlab = c(0,20,40,60,80,100),
             raxlab = c(0,20,40,60,80,100),
             main = "control", 
             top.labels = c("from aorta", "migration", "to aorta"),  label=count_control_table$value,
             gap = 5, labelcex = 1.6, unit=text(0,-2,"normalized counts (%)",cex=1.6), lxcol=color_aISV, rxcol = color_aISV)

dev.off()

pyramid.plot(count_control_table$frequency_control_from_aorta, count_control_table$frequency_control_to_aorta, 
             laxlab = c(0,20,40,60,80,100),
             raxlab = c(0,20,40,60,80,100),
             main = "control", 
             top.labels = c("from aorta", "migration", "to aorta"),  label=count_control_table$value,
             gap = 5, labelcex = 1.6, unit=text(0,-2,"normalized counts (%)",cex=1.6), lxcol=color_aISV, rxcol = color_aISV)

```

```{r plot_migration_from_aorta_distributions_control_vs_Wasp1, echo=FALSE}

from_aorta_Wasp1_table <- table(migration_json$migration_from_aorta$`WaspI [100uM]`$aISV)
to_aorta_Wasp1_table <- table(migration_json$migration_to_aorta$`WaspI [100uM]`$aISV)


to_aorta_Wasp1_table <- data.frame(to_aorta_Wasp1_table)
colnames(to_aorta_Wasp1_table) <- c("value","counts_Wasp1_to_aorta")
from_aorta_Wasp1_table <- data.frame(from_aorta_Wasp1_table)
colnames(from_aorta_Wasp1_table) <- c("value","counts_Wasp1_from_aorta")

count_Wasp1_table <- merge(from_aorta_Wasp1_table, to_aorta_Wasp1_table, all=TRUE)
count_Wasp1_table [is.na(count_Wasp1_table )] <- 0
count_Wasp1_table ["frequency_Wasp1_from_aorta"] <- 100*count_Wasp1_table["counts_Wasp1_from_aorta"]/sum(count_Wasp1_table["counts_Wasp1_from_aorta"])
count_Wasp1_table ["frequency_Wasp1_to_aorta"] <- 100*count_Wasp1_table["counts_Wasp1_to_aorta"]/sum(count_Wasp1_table["counts_Wasp1_to_aorta"])

count_table <- merge(count_control_table, count_Wasp1_table, all=TRUE)
count_table[is.na(count_table)] <- 0

print(count_table)

pdf(paste0(subfolder, 'migration_exchange_aorta_control_vs_Wasp1.pdf'))

pyramid.plot(count_table$frequency_control_from_aorta,count_table$frequency_control_to_aorta, 
             laxlab = c(0,20,40,60,80,100),
             raxlab = c(0,20,40,60,80,100),
             main = "exchange with aorta: control vs. Wasp1", 
             top.labels = c("immigration", "counts", "emigration"), label=count_table$value, 
             gap = 5, labelcex = 1.6, unit=text(0,-2,"normalized counts (%)",cex=1.6), lxcol=color_control_background, rxcol = color_control_background)

pyramid.plot(count_table$frequency_Wasp1_from_aorta,count_table$frequency_Wasp1_to_aorta,
             laxlab = c(0,20,40,60,80,100),
             raxlab = c(0,20,40,60,80,100),
             main = "exchange with aorta: control vs. Wasp1", 
             #top.labels =  c("from_aorta", "migration from aorta", "  to_aorta "), 
             label=count_table$value, space = 0.4,
             gap = 5, labelcex = 1.6, unit=text(0,-2,"Normalized counts (%)",cex=1.6), lxcol=color_aISV, rxcol = color_aISV,
             add = TRUE)

dev.off()

pyramid.plot(count_table$frequency_control_from_aorta,count_table$frequency_control_to_aorta, 
             laxlab = c(0,20,40,60,80,100),
             raxlab = c(0,20,40,60,80,100),
             main = "exchange with aorta: control vs. Wasp1", 
             top.labels = c("immigration", "counts", "emigration"), label=count_table$value, 
             gap = 5, labelcex = 1.6, unit=text(0,-2,"normalized counts (%)",cex=1.6), lxcol=color_control_background, rxcol = color_control_background)

pyramid.plot(count_table$frequency_Wasp1_from_aorta,count_table$frequency_Wasp1_to_aorta,
             laxlab = c(0,20,40,60,80,100),
             raxlab = c(0,20,40,60,80,100),
             main = "exchange with aorta: control vs. Wasp1", 
             #top.labels =  c("from_aorta", "migration from aorta", "  to_aorta "), 
             label=count_table$value, space = 0.4,
             gap = 5, labelcex = 1.6, unit=text(0,-2,"Normalized counts (%)",cex=1.6), lxcol=color_aISV, rxcol = color_aISV,
             add = TRUE)

```

```{r plot_migration_from_aorta_distributions_control_vs_Gata1, echo=FALSE}

from_aorta_Gata1_table <- table(migration_json$migration_from_aorta$Gata1$aISV)
to_aorta_Gata1_table <- table(migration_json$migration_to_aorta$Gata1$aISV)


to_aorta_Gata1_table <- data.frame(to_aorta_Gata1_table)
colnames(to_aorta_Gata1_table) <- c("value","counts_Gata1_to_aorta")
from_aorta_Gata1_table <- data.frame(from_aorta_Gata1_table)
colnames(from_aorta_Gata1_table) <- c("value","counts_Gata1_from_aorta")

count_Gata1_table <- merge(from_aorta_Gata1_table, to_aorta_Gata1_table, all=TRUE)
count_Gata1_table [is.na(count_Gata1_table )] <- 0
count_Gata1_table ["frequency_Gata1_from_aorta"] <- 100*count_Gata1_table["counts_Gata1_from_aorta"]/sum(count_Gata1_table["counts_Gata1_from_aorta"])
count_Gata1_table ["frequency_Gata1_to_aorta"] <- 100*count_Gata1_table["counts_Gata1_to_aorta"]/sum(count_Gata1_table["counts_Gata1_to_aorta"])

count_table <- merge(count_control_table, count_Gata1_table, all=TRUE)
count_table[is.na(count_table)] <- 0

print(count_table)

pdf(paste0(subfolder, 'migration_exchange_aorta_control_vs_Gata1.pdf'))

pyramid.plot(count_table$frequency_control_from_aorta,count_table$frequency_control_to_aorta, 
             laxlab = c(0,20,40,60,80,100),
             raxlab = c(0,20,40,60,80,100),
             main = "exchange with aorta: control vs. Gata1", 
             top.labels = c("immigration", "counts", "emigration"), label=count_table$value, 
             gap = 5, labelcex = 1.6, unit=text(0,-2,"normalized counts (%)",cex=1.6), lxcol=color_control_background, rxcol = color_control_background)

pyramid.plot(count_table$frequency_Gata1_from_aorta,count_table$frequency_Gata1_to_aorta,
             laxlab = c(0,20,40,60,80,100),
             raxlab = c(0,20,40,60,80,100),
             main = "exchange with aorta: control vs. Gata1",  
             label=count_table$value, space = 0.4,
             gap = 5, labelcex = 1.6, unit=text(0,-2,"Normalized counts (%)",cex=1.6), lxcol=color_aISV, rxcol = color_aISV,
             add = TRUE)

dev.off()

pyramid.plot(count_table$frequency_control_from_aorta,count_table$frequency_control_to_aorta, 
             laxlab = c(0,20,40,60,80,100),
             raxlab = c(0,20,40,60,80,100),
             main = "exchange with aorta: control vs. Gata1", 
             top.labels = c("immigration", "counts", "emigration"), label=count_table$value, 
             gap = 5, labelcex = 1.6, unit=text(0,-2,"normalized counts (%)",cex=1.6), lxcol=color_control_background, rxcol = color_control_background)

pyramid.plot(count_table$frequency_Gata1_from_aorta,count_table$frequency_Gata1_to_aorta,
             laxlab = c(0,20,40,60,80,100),
             raxlab = c(0,20,40,60,80,100),
             main = "exchange with aorta: control vs. Gata1",  
             label=count_table$value, space = 0.4,
             gap = 5, labelcex = 1.6, unit=text(0,-2,"Normalized counts (%)",cex=1.6), lxcol=color_aISV, rxcol = color_aISV,
             add = TRUE)


```

```{r plot_migration_from_aorta_distributions_control_vs_Gata1_Wasp1, echo=FALSE}

from_aorta_Gata1_Wasp1_table <- table(migration_json$migration_from_aorta$Gata1_Wasp1$aISV)
to_aorta_Gata1_Wasp1_table <- table(migration_json$migration_to_aorta$Gata1_Wasp1$aISV)


to_aorta_Gata1_Wasp1_table <- data.frame(to_aorta_Gata1_Wasp1_table)
colnames(to_aorta_Gata1_Wasp1_table) <- c("value","counts_Gata1_Wasp1_to_aorta")
from_aorta_Gata1_Wasp1_table <- data.frame(from_aorta_Gata1_Wasp1_table)
colnames(from_aorta_Gata1_Wasp1_table) <- c("value","counts_Gata1_Wasp1_from_aorta")

count_Gata1_Wasp1_table <- merge(from_aorta_Gata1_Wasp1_table, to_aorta_Gata1_Wasp1_table, all=TRUE)
count_Gata1_Wasp1_table [is.na(count_Gata1_Wasp1_table )] <- 0
count_Gata1_Wasp1_table ["frequency_Gata1_Wasp1_from_aorta"] <- 100*count_Gata1_Wasp1_table["counts_Gata1_Wasp1_from_aorta"]/sum(count_Gata1_Wasp1_table["counts_Gata1_Wasp1_from_aorta"])
count_Gata1_Wasp1_table ["frequency_Gata1_Wasp1_to_aorta"] <- 100*count_Gata1_Wasp1_table["counts_Gata1_Wasp1_to_aorta"]/sum(count_Gata1_Wasp1_table["counts_Gata1_Wasp1_to_aorta"])

count_table <- merge(count_control_table, count_Gata1_Wasp1_table, all=TRUE)
count_table[is.na(count_table)] <- 0

print(count_table)

pdf(paste0(subfolder, 'migration_exchange_aorta_control_vs_Gata1_Wasp1.pdf'))

pyramid.plot(count_table$frequency_control_from_aorta,count_table$frequency_control_to_aorta, 
             laxlab = c(0,20,40,60,80,100),
             raxlab = c(0,20,40,60,80,100),
             main = "exchange with aorta: control vs. Gata1-Wasp1", 
             top.labels = c("immigration", "counts", "emigration"), label=count_table$value, 
             gap = 5, labelcex = 1.6, unit=text(0,-2,"normalized counts (%)",cex=1.6), lxcol=color_control_background, rxcol = color_control_background)

pyramid.plot(count_table$frequency_Gata1_Wasp1_from_aorta,count_table$frequency_Gata1_Wasp1_to_aorta,
             laxlab = c(0,20,40,60,80,100),
             raxlab = c(0,20,40,60,80,100),
             main = "exchange with aorta: control vs. Gata1-Wasp1",
             label=count_table$value, space = 0.4,
             gap = 5, labelcex = 1.6, unit=text(0,-2,"Normalized counts (%)",cex=1.6), lxcol=color_aISV, rxcol = color_aISV,
             add = TRUE)

dev.off()

pyramid.plot(count_table$frequency_control_from_aorta,count_table$frequency_control_to_aorta, 
             laxlab = c(0,20,40,60,80,100),
             raxlab = c(0,20,40,60,80,100),
             main = "exchange with aorta: control vs. Gata1-Wasp1", 
             top.labels = c("immigration", "counts", "emigration"), label=count_table$value, 
             gap = 5, labelcex = 1.6, unit=text(0,-2,"normalized counts (%)",cex=1.6), lxcol=color_control_background, rxcol = color_control_background)

pyramid.plot(count_table$frequency_Gata1_Wasp1_from_aorta,count_table$frequency_Gata1_Wasp1_to_aorta,
             laxlab = c(0,20,40,60,80,100),
             raxlab = c(0,20,40,60,80,100),
             main = "exchange with aorta: control vs. Gata1-Wasp1",
             label=count_table$value, space = 0.4,
             gap = 5, labelcex = 1.6, unit=text(0,-2,"Normalized counts (%)",cex=1.6), lxcol=color_aISV, rxcol = color_aISV,
             add = TRUE)

```


